# Change these first
owner: pdsouza # Your GitHub organization or username, where this repository lives
repo: nw-status-page # The name of this repository

sites:
  - name: Unit API (sandbox)
    url: https://api.s.unit.sh
  - name: Unit API (live)
    url: https://api.unit.co/
  - name: Jackson API (dev)
    url: https://api.devjnptw.com
    expectedStatusCodes:
      - 404
  - name: Jackson InstantPay API (prod)
    url: $JACKSON_INSTANTPAY_API_PROD_URL
    method: POST
    headers:
      - "X-API-KEY: $JACKSON_API_PROD_TOKEN"
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 500

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /nw-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NW Status Page
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
